### ISSUE TITLE
404 Dead link to https://print-nanny.com/dashboard/alerts/ from "View History" in the alert bell icon top right of web interface

### ISSUE THREAD

**Issue by CTFishUSA** [bitsy-ai/octoprint-nanny-plugin#103]
- OctoPrint version: N/A
- Print Nanny version: Web portal
- OctoPi (or other OS) version: N/A

**Describe the bug**

**To Reproduce**
1. Go to https://print-nanny.com/dashboard/
2. Click on the bell icon for notifications, whether or not you have a new notification
3. Click on view history which takes to https://print-nanny.com/dashboard/alerts/
4. See error404

**Expected behavior**
Take me to the notification page whcih I think is https://print-nanny.com/alerts/

**Screenshots**
![2021-01-30-203658_1680x1050_scrot](https://user-images.githubusercontent.com/76830938/106372181-32b6e780-633b-11eb-8e6e-0690022f5fe4.png)

**Comment by leigh-johnson** [comment]
Thank you for reporting this! Just deployed a fix. :bowing_woman:
