### ISSUE TITLE
Log to /path/to/.octoprint/logs/plugin_octoprint_nanny.log

### ISSUE THREAD

**Issue by leigh-johnson** [bitsy-ai/octoprint-nanny-plugin#113]
- OctoPrint version: 1.5.x
- Print Nanny version: 0.4.3
- OctoPi (or other OS) version: 0.18

**Describe the bug**
Print Nanny only logs to `/path/to/.octoprint/logs/octoprint.log` (root logger). Other plugins have a file handler configured, which logs to `plugin_pluginname.log`. For example:

```
$ls -ahl ~/.octoprint/logs
total 28K
drwxr-xr-x  2 leigh leigh 4.0K Feb  6 01:00 .
drwxr-xr-x 14 leigh leigh 4.0K Feb  6 01:00 ..
-rw-r--r--  1 leigh leigh  18K Feb  6 01:00 octoprint.log
-rw-r--r--  1 leigh leigh    0 Feb  6 01:00 plugin_pluginmanager_console.log
-rw-r--r--  1 leigh leigh    0 Feb  6 01:00 plugin_softwareupdate_console.log
```

**Expected behavior**
OctoPrint Nanny logs to `/path/to/.octoprint/logs/plugin_octoprint_nanny.log` (in addition to OctoPrint's root log file)

**Comment by CTFishUSA** [comment]
Great idea!
