### ISSUE TITLE
Receive TFLite model version via device configuration topic

### ISSUE THREAD

**Issue by leigh-johnson** [bitsy-ai/octoprint-nanny-plugin#116]
**Describe your Request**
Currently, the model weights are distributed via package data. This makes plugin updates (source distribution from .zip) take much longer than necessary. 

Instead, the device should download the latest model to the plugin data directory. Model version updates will be published via configuration topic: https://cloud.google.com/iot/docs/concepts/devices#device_configuration

As part of this ticket, rip out the fat TensorFlow binary and replace with TFLite runtime. 

** Benchmarks **

0.4.3
```
uccessfully installed OctoPrint-Nanny-0.4.3
pip install --no-cache-dir   10.00s user 1.66s system 58% cpu 19.957 total
```

**Comment by CTFishUSA** [comment]
Is this the end of the 120mb wheel?

**Comment by leigh-johnson** [comment]
> Is this the end of the 120mb wheel?

Yep =) I was using the full TensorFlow binary for some extra profiling stuff that only lives in the full package. This release will switch over to using TensorFlow's runtime package, which has a much smaller footprint.

More info here:
https://www.tensorflow.org/lite/guide/python#about_the_tensorflow_lite_runtime_package

**Comment by leigh-johnson** [comment]
Punting this out to release 0.6.0 for now.
