### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by arut16** [bitsy-ai/octoprint-nanny-plugin#18]
Hi,

I have the last version of Octoprint. Tried to install octo-nanny plugin. Takes around 5min then installation seems to be done but a notification shows install : "unknown" OK. After an octoprint reboot, plugin is not installed...
![image](https://user-images.githubusercontent.com/58274805/103169503-7732fd00-483c-11eb-8bf0-a740dfd094fb.png)
![image](https://user-images.githubusercontent.com/58274805/103169512-8619af80-483c-11eb-993f-0149b445def2.png)
![image](https://user-images.githubusercontent.com/58274805/103169560-0cce8c80-483d-11eb-93a1-65b5cf08be0f.png)
After install : 
![image](https://user-images.githubusercontent.com/58274805/103169580-4c957400-483d-11eb-8169-628af82bcd71.png)

INSTALLATION LOG :

> `Installation du plugin "OctoPrint Nanny" à partir de https://github.com/bitsy-ai/octoprint-nanny-plugin/archive/main.zip ...
/home/pi/oprint/bin/python -m pip --disable-pip-version-check install file:///tmp/tmp2fysfo75/octoprint-nanny-plugin-main.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmp2fysfo75/octoprint-nanny-plugin-main.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (1.5.2)
Collecting tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl
Downloading https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl (151.3 MB)
Requirement already satisfied: numpy in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (1.19.2)
Requirement already satisfied: pillow in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (8.0.1)
Requirement already satisfied: bravado in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (11.0.2)
Requirement already satisfied: pytz in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (2020.4)
Requirement already satisfied: aiohttp in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (3.7.3)
Requirement already satisfied: print-nanny-client in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (0.1.3)
Requirement already satisfied: websockets in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (8.1)
Requirement already satisfied: backoff==1.10.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (1.10.0)
Requirement already satisfied: aioprocessing==1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (1.1.0)
Requirement already satisfied: multiprocessing-logging==0.3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (0.3.1)
Requirement already satisfied: typing_extensions in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.1.0) (3.7.4.3)
Requirement already satisfied: flatbuffers~=1.12.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.12)
Requirement already satisfied: termcolor~=1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.1.0)
Requirement already satisfied: wheel~=0.35 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (0.36.2)
Requirement already satisfied: grpcio~=1.32.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.32.0)
Requirement already satisfied: h5py~=2.10.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (2.10.0)
Requirement already satisfied: tensorboard~=2.4 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (2.4.0)
Requirement already satisfied: six~=1.15.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.15.0)
Requirement already satisfied: tensorflow-estimator<2.5.0,>=2.4.0rc0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (2.4.0)
Requirement already satisfied: gast==0.3.3 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (0.3.3)
Requirement already satisfied: absl-py~=0.10 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (0.11.0)
Requirement already satisfied: google-pasta~=0.2 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (0.2.0)
Requirement already satisfied: opt-einsum~=3.3.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (3.3.0)
Requirement already satisfied: astunparse~=1.6.3 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.6.3)
Requirement already satisfied: protobuf>=3.9.2 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (3.14.0)
Requirement already satisfied: wrapt~=1.12.1 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.12.1)
Requirement already satisfied: keras-preprocessing~=1.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.1.2)
Requirement already satisfied: werkzeug>=0.11.15 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (2.25.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.7.0)
Requirement already satisfied: markdown>=2.6.8 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (3.1.1)
Requirement already satisfied: setuptools>=41.0.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (51.1.0.post20201221)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (0.4.2)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.24.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/pi/oprint/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/pi/oprint/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (4.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/pi/oprint/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (4.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/pi/oprint/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/pi/oprint/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (0.4.8)
Requirement already satisfied: idna<3,>=2.5 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (2020.12.5)
Requirement already satisfied: oauthlib>=3.0.0 in /home/pi/oprint/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.1.0) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.1.0) (5.1.0)
Requirement already satisfied: attrs>=17.3.0 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.1.0) (20.3.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.1.0) (1.6.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.1.0) (3.0.1)
Requirement already satisfied: monotonic in /home/pi/oprint/lib/python3.7/site-packages (from bravado->OctoPrint-Nanny==0.1.0) (1.5)
Requirement already satisfied: bravado-core>=5.16.1 in /home/pi/oprint/lib/python3.7/site-packages (from bravado->OctoPrint-Nanny==0.1.0) (5.17.0)
Requirement already satisfied: simplejson in /home/pi/oprint/lib/python3.7/site-packages (from bravado->OctoPrint-Nanny==0.1.0) (3.17.2)
Requirement already satisfied: pyyaml in /home/pi/oprint/lib/python3.7/site-packages (from bravado->OctoPrint-Nanny==0.1.0) (5.3.1)
Requirement already satisfied: python-dateutil in /home/pi/oprint/lib/python3.7/site-packages (from bravado->OctoPrint-Nanny==0.1.0) (2.8.1)
Requirement already satisfied: msgpack in /home/pi/oprint/lib/python3.7/site-packages (from bravado->OctoPrint-Nanny==0.1.0) (1.0.2)
Requirement already satisfied: swagger-spec-validator>=2.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (2.7.3)
Requirement already satisfied: jsonref in /home/pi/oprint/lib/python3.7/site-packages (from bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (0.2)
Requirement already satisfied: jsonschema[format]>=2.5.1 in /home/pi/oprint/lib/python3.7/site-packages (from bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (3.2.0)
Requirement already satisfied: importlib-metadata in /home/pi/oprint/lib/python3.7/site-packages (from jsonschema[format]>=2.5.1->bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (3.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/pi/oprint/lib/python3.7/site-packages (from jsonschema[format]>=2.5.1->bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (0.17.3)
Requirement already satisfied: webcolors in /home/pi/oprint/lib/python3.7/site-packages (from jsonschema[format]>=2.5.1->bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (1.11.1)
Requirement already satisfied: jsonpointer>1.13 in /home/pi/oprint/lib/python3.7/site-packages (from jsonschema[format]>=2.5.1->bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (2.0)
Requirement already satisfied: strict-rfc3339 in /home/pi/oprint/lib/python3.7/site-packages (from jsonschema[format]>=2.5.1->bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (0.7)
Requirement already satisfied: rfc3987 in /home/pi/oprint/lib/python3.7/site-packages (from jsonschema[format]>=2.5.1->bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (1.3.8)
Requirement already satisfied: zipp>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from importlib-metadata->jsonschema[format]>=2.5.1->bravado-core>=5.16.1->bravado->OctoPrint-Nanny==0.1.0) (3.4.0)
Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.4)
Requirement already satisfied: cachelib<1,>=0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.1.1)
Requirement already satisfied: zeroconf<0.25,>=0.24 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.24.5)
Requirement already satisfied: websocket-client<1,>=0.57 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.57.0)
Requirement already satisfied: Jinja2<3,>=2.11.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (2.11.2)
Requirement already satisfied: psutil<6,>=5.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (5.8.0)
Requirement already satisfied: frozendict<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.2)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.5.0)
Requirement already satisfied: watchdog==0.10.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.10.4)
Requirement already satisfied: netaddr<1,>=0.7.19 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.8.0)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.1.1)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2020.09.23 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (2020.9.23)
Requirement already satisfied: tornado==5.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (5.1.1)
Requirement already satisfied: flask<2,>=1.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.1.2)
Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (3.5)
Requirement already satisfied: feedparser<7,>=6.0.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (6.0.2)
Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (2.8.5)
Requirement already satisfied: unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.4.21)
Requirement already satisfied: pkginfo<2,>=1.5.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.6.1)
Requirement already satisfied: netifaces<1,>=0.10.9 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.10.9)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.0.7)
Requirement already satisfied: Click<8,>=7.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (7.1.2)
Requirement already satisfied: OctoPrint-FileCheck>=2020.08.07 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (2020.8.7)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.1.0)
Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.0.0)
Requirement already satisfied: sarge==0.1.5post0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.1.5.post0)
Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.18.2)
Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (1.2.0)
Requirement already satisfied: sentry-sdk<1,>=0.15.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.19.5)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (2.0)
Requirement already satisfied: emoji<1,>=0.5.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (0.6.0)
Requirement already satisfied: regex!=2018.11.6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.1.0) (2020.11.13)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from watchdog==0.10.4->OctoPrint->OctoPrint-Nanny==0.1.0) (0.1.2)
Requirement already satisfied: sgmllib3k in /home/pi/oprint/lib/python3.7/site-packages (from feedparser<7,>=6.0.2->OctoPrint->OctoPrint-Nanny==0.1.0) (1.0.0)
Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-Nanny==0.1.0) (2.0)
Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-Nanny==0.1.0) (2.9.0)
Requirement already satisfied: ifaddr in /home/pi/oprint/lib/python3.7/site-packages (from zeroconf<0.25,>=0.24->OctoPrint->OctoPrint-Nanny==0.1.0) (0.1.7)
Building wheels for collected packages: OctoPrint-Nanny
Building wheel for OctoPrint-Nanny (setup.py): started
Building wheel for OctoPrint-Nanny (setup.py): finished with status 'done'
Created wheel for OctoPrint-Nanny: filename=OctoPrint_Nanny-0.1.0-py3-none-any.whl size=13180098 sha256=5da94f322da3500dfeca6a2239304436ebf5f0bbffb2c97dc03ed852a3ed7f72
Stored in directory: /tmp/pip-ephem-wheel-cache-z3jzrnqd/wheels/71/b3/95/4be3317739eb167b5edc20d873860d9f459d78c7c3d6497557
Successfully built OctoPrint-Nanny
Installing collected packages: OctoPrint-Nanny
Attempting uninstall: OctoPrint-Nanny
Found existing installation: OctoPrint-Nanny 0.1.0
Uninstalling OctoPrint-Nanny-0.1.0:
Successfully uninstalled OctoPrint-Nanny-0.1.0
Successfully installed OctoPrint-Nanny-0.1.0
Fait !`

**Comment by arut16** [comment]
Maybe there some missing libreries...

**Comment by EuKeck** [comment]
Applies to me as well.
I am not able to install the plugin on freshly installed  OctoPi Version 0.18.0 (RC1)
(using a Raspberry Pi 2 Model B Rev 1.1)

![image](https://user-images.githubusercontent.com/44929578/103182797-6622d400-48ae-11eb-9c8e-006bdf1eacd3.png)


Best regards 
E. Keck

**Comment by DrDrache** [comment]
> Applies to me as well.
> I am not able to install the plugin on freshly installed OctoPi Version 0.18.0 (RC1)
> (using a Raspberry Pi 2 Model B Rev 1.1)
> 
> ![image](https://user-images.githubusercontent.com/44929578/103182797-6622d400-48ae-11eb-9c8e-006bdf1eacd3.png)
> 
> Best regards
> E. Keck

same here - same build (octopi .18 RC1)

**Comment by leigh-johnson** [comment]
Thank you for the version/platform info! Reproduced this issue, fix incoming in 0.1.1. :bowing_woman:

**Comment by leigh-johnson** [comment]
:wave: Hey y'all! The fix for this ended up in release v0.2.0. Please re-open if this does not work for you. Thanks!

https://github.com/bitsy-ai/octoprint-nanny-plugin/releases/tag/v0.2.0
