### ISSUE TITLE
Install process for RPi 4 2 GB Octopi

### ISSUE THREAD

**Issue by CTFishUSA** [bitsy-ai/octoprint-nanny-plugin#34]
Trying the install this evening on my RPI 4 2GB that was built with an Octopi image.

First error: 
AttributeError: 'tuple' object has no attribute 'machine'

This is surely a dependency problem.  I will give a shot at update / upgrade, and check again.  Then I'll start pulling in the dependent packages manually ...

Since i'm at it i'll go to the 64-bit kernel ...

Octopi was running fine as-is, but here we go!

Also, Octoprint said this was "incompatible" and I tried to run the install from URL to the .zip

**Comment by CTFishUSA** [comment]
No dice.  Same error.  Completed the update and am now at 64-bit.

**Comment by CTFishUSA** [comment]
Next try:
Unzip and run the install.sh from prompt

pi@octopi:/tmp $ ls -l
total 8
drwx------ 3 root root 4096 Jan  9 21:17 systemd-private-728fd60328a14664b8845f7072bec57a-systemd-timesyncd.service-xqT5Bx
drwx------ 2 pi   pi   4096 Jan  9 21:19 tmpCsIVbJ
pi@octopi:/tmp $ cd tmpCsIVbJ/
pi@octopi:/tmp/tmpCsIVbJ $ ls
octoprint-nanny-plugin-main.zip
pi@octopi:/tmp/tmpCsIVbJ $ unzip
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer
pi@octopi:/tmp/tmpCsIVbJ $ unzip octoprint-nanny-plugin-main.zip 
Archive:  octoprint-nanny-plugin-main.zip
84e9837c70d19a29f58b6b5958c634be62890d6b
   creating: octoprint-nanny-plugin-main/
  inflating: octoprint-nanny-plugin-main/.editorconfig  
  inflating: octoprint-nanny-plugin-main/.gitignore  
  inflating: octoprint-nanny-plugin-main/LICENSE  
  inflating: octoprint-nanny-plugin-main/MANIFEST.in  
  inflating: octoprint-nanny-plugin-main/Makefile  
  inflating: octoprint-nanny-plugin-main/README.md  
  inflating: octoprint-nanny-plugin-main/babel.cfg  
  inflating: octoprint-nanny-plugin-main/dev-requirements.txt  
   creating: octoprint-nanny-plugin-main/docs/
   creating: octoprint-nanny-plugin-main/docs/images/
  inflating: octoprint-nanny-plugin-main/docs/images/logo.jpg  
  inflating: octoprint-nanny-plugin-main/docs/images/screenshot_1.png  
  inflating: octoprint-nanny-plugin-main/docs/images/screenshot_2.png  
  inflating: octoprint-nanny-plugin-main/docs/images/screenshot_3.png  
  inflating: octoprint-nanny-plugin-main/docs/images/screenshot_4.png  
  inflating: octoprint-nanny-plugin-main/docs/images/screenshot_5.png  
   creating: octoprint-nanny-plugin-main/extras/
  inflating: octoprint-nanny-plugin-main/extras/README.txt  
  inflating: octoprint-nanny-plugin-main/extras/octoprint_nanny.md  
   creating: octoprint-nanny-plugin-main/hooks/
  inflating: octoprint-nanny-plugin-main/hooks/pre-commit  
  inflating: octoprint-nanny-plugin-main/install.sh  
  inflating: octoprint-nanny-plugin-main/nginx.conf  
  inflating: octoprint-nanny-plugin-main/octoprint-nanny.workspace.code-workspace  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/__init__.py  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/clients/
 extracting: octoprint-nanny-plugin-main/octoprint_nanny/clients/__init__.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/clients/honeycomb.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/clients/mqtt.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/clients/rest.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/clients/websocket.py  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/data/
   creating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/0.post.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/0.pre.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/1.post.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/1.pre.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/2.post.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/2.pre.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/3.post.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/3.pre.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/4.post.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/4.pre.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/5.post.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/5.pre.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/6.post.jpg  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/images/6.pre.jpg  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/data/tflite-print3d-2020-10-23T18:00:41.136Z/
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/tflite-print3d-2020-10-23T18:00:41.136Z/dict.txt  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/tflite-print3d-2020-10-23T18:00:41.136Z/model.tflite  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/data/tflite-print3d-2020-10-23T18:00:41.136Z/tflite_metadata.json  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/errors.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/manager.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/plugins.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/predictor.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/python.json  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/python.yaml  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/static/
   creating: octoprint-nanny-plugin-main/octoprint_nanny/static/css/
 extracting: octoprint-nanny-plugin-main/octoprint_nanny/static/css/nanny.css  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/static/img/
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/static/img/ignore_mask_example.gif  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/static/img/logo-square-excited.png  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/static/img/print_nanny_logo.png  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/static/img/sleeping.png  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/static/img/wizard_example.jpg  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/static/js/
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/static/js/nanny.js  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/static/less/
 extracting: octoprint-nanny-plugin-main/octoprint_nanny/static/less/nanny.less  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/static/vendor/
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/static/vendor/swagger-client@3.12.0.browser.min.js  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/templates/
 extracting: octoprint-nanny-plugin-main/octoprint_nanny/templates/README.txt  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/templates/octoprint_nanny_navbar.jinja2  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/templates/octoprint_nanny_settings.jinja2  
 extracting: octoprint-nanny-plugin-main/octoprint_nanny/templates/octoprint_nanny_settings_advanced.jinja2  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/templates/octoprint_nanny_settings_shared.jinja2  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/templates/octoprint_nanny_tab.jinja2  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/templates/octoprint_nanny_wizard.jinja2  
   creating: octoprint-nanny-plugin-main/octoprint_nanny/utils/
 extracting: octoprint-nanny-plugin-main/octoprint_nanny/utils/__init__.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/utils/encoder.py  
  inflating: octoprint-nanny-plugin-main/octoprint_nanny/utils/visualization.py  
   creating: octoprint-nanny-plugin-main/playbooks/
  inflating: octoprint-nanny-plugin-main/playbooks/install.yml  
 extracting: octoprint-nanny-plugin-main/playbooks/requirements.yml  
   creating: octoprint-nanny-plugin-main/playbooks/templates/
  inflating: octoprint-nanny-plugin-main/playbooks/templates/mjpg-streamer.service  
  inflating: octoprint-nanny-plugin-main/requirements.txt  
  inflating: octoprint-nanny-plugin-main/setup.cfg  
  inflating: octoprint-nanny-plugin-main/setup.py  
   creating: octoprint-nanny-plugin-main/tests/
 extracting: octoprint-nanny-plugin-main/tests/test_manager.py  
  inflating: octoprint-nanny-plugin-main/tests/test_mqtt.py  
  inflating: octoprint-nanny-plugin-main/tests/test_predictor.py  
  inflating: octoprint-nanny-plugin-main/tests/test_websocket.py  
   creating: octoprint-nanny-plugin-main/translations/
  inflating: octoprint-nanny-plugin-main/translations/README.txt  
pi@octopi:/tmp/tmpCsIVbJ $ ls
octoprint-nanny-plugin-main  octoprint-nanny-plugin-main.zip
pi@octopi:/tmp/tmpCsIVbJ $ cd octoprint-nanny-plugin-main/
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ ls
LICENSE               nginx.conf
MANIFEST.in           octoprint-nanny.workspace.code-workspace
Makefile              octoprint_nanny
README.md             playbooks
babel.cfg             requirements.txt
dev-requirements.txt  setup.cfg
docs                  setup.py
extras                tests
hooks                 translations
install.sh
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ build
-bash: build: command not found
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ Make
-bash: Make: command not found
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ make
rm -fr build/
rm -fr dist/
rm -fr .eggs/
find . -name '*.egg-info' -exec rm -fr {} +
find . -name '*.egg' -exec rm -f {} +
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ ls
LICENSE               nginx.conf
MANIFEST.in           octoprint-nanny.workspace.code-workspace
Makefile              octoprint_nanny
README.md             playbooks
babel.cfg             requirements.txt
dev-requirements.txt  setup.cfg
docs                  setup.py
extras                tests
hooks                 translations
install.sh
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ inst
install        install-info   installkernel  installwatch   instmodsh
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ install.
-bash: install.: command not found
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ ./install.sh
-bash: ./install.sh: Permission denied
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ chmod +x install.sh
pi@octopi:/tmp/tmpCsIVbJ/octoprint-nanny-plugin-main $ ./install.sh
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[sudo] password for pi: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libatlas-base-dev is already the newest version (3.10.3-8+rpi1).
The following packages were automatically installed and are no longer required:
  libllvm8 rpi-eeprom-images
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.13.4-1).
imagemagick is already the newest version (8:6.9.10.23+dfsg-2.1+deb10u1).
libjpeg62-turbo-dev is already the newest version (1:1.5.2-2+deb10u1).
libv4l-dev is already the newest version (1.16.3-3).
subversion is already the newest version (1.10.4-1+deb10u1).
ffmpeg is already the newest version (7:4.1.6-1~deb10u1+rpt1).
The following packages were automatically installed and are no longer required:
  libllvm8 rpi-eeprom-images
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by CTFishUSA** [comment]
Next, i'm getting pip ... surely I had this already?

**Comment by dzervas** [comment]
Are you running python3 octoprint?

**Comment by CTFishUSA** [comment]
Worked through the dev_requirements.  Now to try the plugin.

**Comment by CTFishUSA** [comment]
> Are you running python3 octoprint?

How?

**Comment by CTFishUSA** [comment]
Found this ... https://octoprint.org/blog/2020/09/10/upgrade-to-py3/

**Comment by CTFishUSA** [comment]
OK, I ran the upgrade-to-py3 script from above.  Octoprint is now at Python3. 
Also updated Octolapse once the server came back.

Plugin installed using the plugin manager, but errors out with
 NameError: name 'tensorflow' is not defined
I think that's someone else's bug

**Comment by CTFishUSA** [comment]
I'll check when 0.2.3 is out, looks like the tensorflow is being addressed in that release.

**Comment by leigh-johnson** [comment]
Thanks for the report! Let me know how the 0.2.3 installation goes.
