### ISSUE TITLE
problems with permissions at install, and internal error during deivce registration

### ISSUE THREAD

**Issue by libelred** [bitsy-ai/octoprint-nanny-plugin#53]
Installation via octoprint plugin manager fails.  
installation using sudo pip installs, but fails when registering the device.

using octopi 0.18rc
[pip.log](https://github.com/bitsy-ai/octoprint-nanny-plugin/files/5793417/pip.log)
[octoprint (6).log](https://github.com/bitsy-ai/octoprint-nanny-plugin/files/5793418/octoprint.6.log)
[plugin_pluginmanager_console (1).log](https://github.com/bitsy-ai/octoprint-nanny-plugin/files/5793419/plugin_pluginmanager_console.1.log)

**Comment by leigh-johnson** [comment]
Hey @libelred, thanks for opening this issue. Looks like Print Nanny's API was unavailable when you tried this. 

Can you update to the latest version of the plugin and try again? Thank you!
