### ISSUE TITLE
Unable to install plugin via manager - Octopi .18 RC2 32bit

### ISSUE THREAD

**Issue by DrDrache** [bitsy-ai/octoprint-nanny-plugin#55]
I switched back to 32bit Octopi .18 as the new 64bit is seriously broken - will go back to 64bit testing when a 64bit version is stable again.

I attempted to install the plugin and get this message (full console logs attached):

2021-01-13 13:39:11,155 > Building wheel for OctoPrint-Nanny (setup.py): started
2021-01-13 13:39:12,465 > Building wheel for OctoPrint-Nanny (setup.py): finished with status 'error'
2021-01-13 13:39:12,481 > Running setup.py clean for OctoPrint-Nanny
2021-01-13 13:39:12,985 ! ERROR: Command errored out with exit status 1:
2021-01-13 13:39:12,986 ! command: /home/pi/oprint/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-18oufm_y/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-18oufm_y/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-pjn3ekc4
2021-01-13 13:39:12,986 ! cwd: /tmp/pip-req-build-18oufm_y/

2021-01-13 13:39:12,996 ! Running PLATFORM_INSTALL command: ['apt-get', 'update']
2021-01-13 13:39:12,996 ! PLATFORM_INSTALL Command output: b'Reading package lists...\nE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)\nE: Unable to lock directory /var/lib/apt/lists/\nW: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)\nW: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)\n'
2021-01-13 13:39:12,996 ! Running PLATFORM_INSTALL command: ['sudo', 'apt-get', 'update']
2021-01-13 13:39:12,996 ! PLATFORM_INSTALL Command output: b'sudo: no tty present and no askpass program specified\n'

[plugin_pluginmanager_console.log](https://github.com/bitsy-ai/octoprint-nanny-plugin/files/5808956/plugin_pluginmanager_console.log)

**Comment by nmsmith22389** [comment]
I'm having the same problem.

**Comment by MambaRoja** [comment]
unable to install, no error message:



Installing plugin "OctoPrint Nanny" from https://github.com/bitsy-ai/octoprint-nanny-plugin/archive/main.zip.../home/pi/oprint/bin/python -m pip --disable-pip-version-check install file:///tmp/tmpgn2m80ob/octoprint-nanny-plugin-main.zip --no-cache-dirLooking in indexes: https://pypi.org/simple, https://www.piwheels.org/simpleProcessing /tmp/tmpgn2m80ob/octoprint-nanny-plugin-main.zipRequirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (1.5.3)Collecting tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whlDownloading https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl (151.3 MB)Requirement already satisfied: numpy in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (1.19.4)Requirement already satisfied: pillow in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (8.0.1)Requirement already satisfied: pytz in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (2020.4)Requirement already satisfied: aiohttp in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (3.7.3)Requirement already satisfied: print-nanny-client~=0.3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (0.3.1)Requirement already satisfied: websockets in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (8.1)Requirement already satisfied: backoff==1.10.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (1.10.0)Requirement already satisfied: aioprocessing==1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (1.1.0)Requirement already satisfied: multiprocessing-logging==0.3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (0.3.1)Requirement already satisfied: jwt in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (1.1.0)Requirement already satisfied: paho-mqtt==1.5.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (1.5.1)Requirement already satisfied: honeycomb-beeline in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (2.16.1)Requirement already satisfied: typing_extensions in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-Nanny==0.3.4) (3.7.4.3)Requirement already satisfied: grpcio~=1.32.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.32.0)Requirement already satisfied: protobuf>=3.9.2 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (3.14.0)Requirement already satisfied: h5py~=2.10.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (2.10.0)Requirement already satisfied: flatbuffers~=1.12.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.12)Requirement already satisfied: astunparse~=1.6.3 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.6.3)Requirement already satisfied: termcolor~=1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.1.0)Requirement already satisfied: keras-preprocessing~=1.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.1.2)Requirement already satisfied: six~=1.15.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.15.0)Requirement already satisfied: opt-einsum~=3.3.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (3.3.0)Requirement already satisfied: google-pasta~=0.2 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (0.2.0)Requirement already satisfied: wheel~=0.35 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (0.36.2)Requirement already satisfied: wrapt~=1.12.1 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.12.1)Requirement already satisfied: gast==0.3.3 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (0.3.3)Requirement already satisfied: tensorboard~=2.4 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (2.4.0)Requirement already satisfied: tensorflow-estimator<2.5.0,>=2.4.0rc0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (2.4.0)Requirement already satisfied: absl-py~=0.10 in /home/pi/oprint/lib/python3.7/site-packages (from tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (0.11.0)Requirement already satisfied: python-dateutil in /home/pi/oprint/lib/python3.7/site-packages (from print-nanny-client~=0.3.1->OctoPrint-Nanny==0.3.4) (2.8.1)Requirement already satisfied: urllib3>=1.25.3 in /home/pi/oprint/lib/python3.7/site-packages (from print-nanny-client~=0.3.1->OctoPrint-Nanny==0.3.4) (1.26.2)Requirement already satisfied: fastavro>=1.2.3 in /home/pi/oprint/lib/python3.7/site-packages (from print-nanny-client~=0.3.1->OctoPrint-Nanny==0.3.4) (1.3.0)Requirement already satisfied: chardet<4.0,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.3.4) (3.0.4)Requirement already satisfied: async-timeout<4.0,>=3.0 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.3.4) (3.0.1)Requirement already satisfied: attrs>=17.3.0 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.3.4) (20.3.0)Requirement already satisfied: multidict<7.0,>=4.5 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.3.4) (5.1.0)Requirement already satisfied: yarl<2.0,>=1.0 in /home/pi/oprint/lib/python3.7/site-packages (from aiohttp->OctoPrint-Nanny==0.3.4) (1.6.3)Requirement already satisfied: markdown>=2.6.8 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (3.1.1)Requirement already satisfied: setuptools>=41.0.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (51.0.0)Requirement already satisfied: werkzeug>=0.11.15 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.0.1)Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.7.0)Requirement already satisfied: google-auth<2,>=1.6.3 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.24.0)Requirement already satisfied: requests<3,>=2.21.0 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (2.25.1)Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/pi/oprint/lib/python3.7/site-packages (from tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (0.4.2)Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/pi/oprint/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (0.2.8)Requirement already satisfied: rsa<5,>=3.1.4 in /home/pi/oprint/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (4.0)Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/pi/oprint/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (4.2.0)Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/pi/oprint/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (1.3.0)Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/pi/oprint/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (0.4.8)Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (2020.12.5)Requirement already satisfied: idna<3,>=2.5 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (2.10)Requirement already satisfied: oauthlib>=3.0.0 in /home/pi/oprint/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.4->tensorflow@ https://github.com/bitsy-ai/tensorflow-arm-bin/releases/download/v2.4.0/tensorflow-2.4.0-cp37-none-linux_armv7l.whl->OctoPrint-Nanny==0.3.4) (3.1.0)Requirement already satisfied: libhoney>=1.7.0 in /home/pi/oprint/lib/python3.7/site-packages (from honeycomb-beeline->OctoPrint-Nanny==0.3.4) (1.10.0)Requirement already satisfied: statsd<4.0.0,>=3.3.0 in /home/pi/oprint/lib/python3.7/site-packages (from libhoney>=1.7.0->honeycomb-beeline->OctoPrint-Nanny==0.3.4) (3.3.0)Requirement already satisfied: cryptography<=3.2.1,>2.9.2 in /home/pi/oprint/lib/python3.7/site-packages (from jwt->OctoPrint-Nanny==0.3.4) (3.2.1)Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/pi/oprint/lib/python3.7/site-packages (from cryptography<=3.2.1,>2.9.2->jwt->OctoPrint-Nanny==0.3.4) (1.14.4)Requirement already satisfied: pycparser in /home/pi/oprint/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography<=3.2.1,>2.9.2->jwt->OctoPrint-Nanny==0.3.4) (2.20)Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.2.0)Requirement already satisfied: emoji<1,>=0.5.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.6.0)Requirement already satisfied: unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.4.21)Requirement already satisfied: flask<2,>=1.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.1.2)Requirement already satisfied: websocket-client<1,>=0.57 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.57.0)Requirement already satisfied: psutil<6,>=5.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (5.8.0)Requirement already satisfied: frozendict<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.2)Requirement already satisfied: feedparser<7,>=6.0.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (6.0.2)Requirement already satisfied: sentry-sdk<1,>=0.15.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.19.5)Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.0.0)Requirement already satisfied: netaddr<1,>=0.7.19 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.8.0)Requirement already satisfied: Click<8,>=7.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (7.1.2)Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.1.0)Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (3.5)Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.0.7)Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.5.0)Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (2.0)Requirement already satisfied: Jinja2<3,>=2.11.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (2.11.2)Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.4)Requirement already satisfied: tornado==5.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (5.1.1)Requirement already satisfied: cachelib<1,>=0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.1.1)Requirement already satisfied: OctoPrint-FileCheck>=2020.08.07 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (2020.8.7)Requirement already satisfied: netifaces<1,>=0.10.9 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.10.9)Requirement already satisfied: sarge==0.1.5post0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.1.5.post0)Requirement already satisfied: zeroconf<0.25,>=0.24 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.24.5)Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.18.2)Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (2.8.5)Requirement already satisfied: OctoPrint-FirmwareCheck>=2020.09.23 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (2020.9.23)Requirement already satisfied: PyYAML<6,>=5.3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (5.3.1)Requirement already satisfied: regex!=2018.11.6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (2020.11.13)Requirement already satisfied: watchdog==0.10.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (0.10.4)Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.1.1)Requirement already satisfied: pkginfo<2,>=1.5.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-Nanny==0.3.4) (1.6.1)Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from watchdog==0.10.4->OctoPrint->OctoPrint-Nanny==0.3.4) (0.1.2)Requirement already satisfied: sgmllib3k in /home/pi/oprint/lib/python3.7/site-packages (from feedparser<7,>=6.0.2->OctoPrint->OctoPrint-Nanny==0.3.4) (1.0.0)Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-Nanny==0.3.4) (2.0)Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-Nanny==0.3.4) (2.9.0)Requirement already satisfied: ifaddr in /home/pi/oprint/lib/python3.7/site-packages (from zeroconf<0.25,>=0.24->OctoPrint->OctoPrint-Nanny==0.3.4) (0.1.7)Building wheels for collected packages: OctoPrint-NannyBuilding wheel for OctoPrint-Nanny (setup.py): startedBuilding wheel for OctoPrint-Nanny (setup.py): finished with status 'done'Created wheel for OctoPrint-Nanny: filename=OctoPrint_Nanny-0.3.4-py3-none-any.whl size=13267797 sha256=f5702acbec650fa12ef67ba5c379be25cadb1bfa1afeda469f8cbd0defd79594Stored in directory: /tmp/pip-ephem-wheel-cache-f5vyyt84/wheels/73/8d/55/3fe495164b18e93c657c99db2927b43657359adce3bcfee315Successfully built OctoPrint-NannyInstalling collected packages: OctoPrint-NannyAttempting uninstall: OctoPrint-NannyFound existing installation: OctoPrint-Nanny 0.3.4Uninstalling OctoPrint-Nanny-0.3.4:Successfully uninstalled OctoPrint-Nanny-0.3.4Successfully installed OctoPrint-Nanny-0.3.4Done!

**Comment by MambaRoja** [comment]
[octoprint.log](https://github.com/bitsy-ai/octoprint-nanny-plugin/files/5860995/octoprint.log)

**Comment by leigh-johnson** [comment]
Hey @MambaRoja, thanks for the logs. Can you SSH into your Raspberry Pi and run:

`sudo apt-get update && sudo apt-get install libatlas3-base`

This will install ATLAS (Automatically Tuned Linear Alebra Software) C libraries. 

After that, reinstall the Print Nanny plugin and restart OctoPrint.

**Comment by leigh-johnson** [comment]
Heyo, closing this for now. Please re-open if you continue to experience installation issues! I've also added these steps to the OctoPrint Setup guide: https://help.print-nanny.com/octoprint-plugin-setup/#install-prerequisites

Thank you for the report! bowing_woman:

**Comment by MambaRoja** [comment]
Sorry for the delay, it is working now!

Thanks

MambaRoja
