### ISSUE TITLE
setup.py os.uname().machine is not a good fit for Pi4 with 64bit kernel and 32bit userland -- tensorflow install fail at 0.3.0

### ISSUE THREAD

**Issue by CTFishUSA** [bitsy-ai/octoprint-nanny-plugin#63]
setup.py

arch = os.uname().machine
is returning the kernel version of my Pi4 (aarch64) but  I have the 32bit userland.  What runs in this situation is the armv7l tensorflow wheel.

This causes an install failure of tensorflow.  Workaround is to hardcode arch = "armv7l" for this situation (64bit kernel, 32bit userland).  

If practical, find alternative test for arch

**Comment by CTFishUSA** [comment]
Here's my suggestion.  Right after:

arch = os.uname().machine

Add this statement (and some situational comments):

if platform.architecture()[0]=='32bit': arch="armv7l"

**Comment by leigh-johnson** [comment]
Thank you so much for following up on this! :bowing_woman: Especially appreciate that you took the time to debug and figure out an alternative. 

Hopefully this covers most cases. :crossed_fingers: 
https://github.com/bitsy-ai/octoprint-nanny-plugin/commit/acf3d9cc1accb9a1050564a2e6cc87c799b43c0d#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R61
