### ISSUE TITLE
email screenshot bug

### ISSUE THREAD

**Issue by PowerChaos** [bitsy-ai/octoprint-nanny-plugin#97]
- OctoPrint version: N/A
- Print Nanny version: 0.40
- OctoPi (or other OS) version: N/A

**Describe the bug**
on print start or really any notification it sends a email with a suposed picture in it
problem is that the link trows out a 403 error , not authenticated to see
maybe it would be better to directly send the image instead from google drive ?

**To Reproduce**
1. Go to 'homepage'
2. Click on 'start a print'
3. Scroll down to 'the same page'
4. See error ' the link you see in the email'

**Expected behavior**
if i click on the image i like to see the image , else there is no point in sending a image
would also be nicer to send the picture instead , now it is just a link with permission errors

**Screenshots**
https://storage.googleapis.com/print-nanny-prod/media/uploads/remote_control_snapshot/2021/01/28/391.jpg?Expires=1611927321&amp;GoogleAccessId=dataflow%40print-nanny.iam.gserviceaccount.com&amp;Signature=pmE1KwmcPwmhiKgo1bDehRkZenSHqd1dhnwHqkM3MuACxSB72qlmK4%2Bj0uVzLZcY6bsWZGLnwctmJTs12t3tHvzYWrkNx7OhP3No%2F8deKM4FsEIyxWQ%2BiXxaoQsXGwNdS48CNUG1jixpLUQ7%2F35erzf1cUA4TCcnFFSBSQ6lZuU6cBYil2%2F7DlF8TKe4BbWLyENnVHJeRv4BilGSmLLq2ijLW%2FL%2BTP1gl8BjtzO3da1cWMX5KJC01AGhYOH0N8FQNpqKAtm1DH0mcllY5B3NgHtZQCFGFtOxzV5ETlOckeF6gJkl7nuskaCJ35tGqnM1Vo4%2BCQbFTm%2BtgLJnjpblBg%3D%3D

instead screenshot i just give you the link that i get in the email :D

Greetings from PowerChaos

**Comment by MambaRoja** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
</Details>
</Error>

email error
